/* REAL LINE original adaptive soundtrack. WebAudio synthesis, no external assets. */
(()=>{"use strict";
const K="real-line-audio-enabled",M="real-line-audio-mode-v1";
let ctx=null,master=null,music=null,timer=null,step=0,scene="world",enabled=false,preference="epic",next=0;
try{enabled=localStorage.getItem(K)==="1";preference=localStorage.getItem(M)||"epic"}catch{}
const Audio=window.AudioContext||window.webkitAudioContext;
const midi=n=>440*Math.pow(2,(n-69)/12);
function init(){if(!Audio)return false;if(!ctx){ctx=new Audio();master=ctx.createGain();master.gain.value=.25;master.connect(ctx.destination);music=ctx.createGain();music.gain.value=.55;music.connect(master)}if(ctx.state==="suspended")ctx.resume().catch(()=>{});return true}
function voice(n,d=.3,type="sine",v=.25,at=null,dest=music,attack=.018){if(!ctx||ctx.state!=="running")return;const t=at??ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(typeof n==="number"&&n>120?n:midi(n),t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,v),t+attack);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(dest);o.start(t);o.stop(t+d+.04)}
function pluck(n,at,v=.2){voice(midi(n),.42,"triangle",v,at,music,.006);voice(midi(n)*2,.13,"sine",v*.24,at,music,.004)}
function pad(n,at,d=1.6,v=.07){voice(midi(n),d,"sine",v,at,music,.23);voice(midi(n+12),d*.85,"triangle",v*.27,at,music,.2)}
function drum(kind,at,v=.2){if(!ctx||ctx.state!=="running")return;const o=ctx.createOscillator(),g=ctx.createGain(),t=at;o.type=kind==="kick"?"sine":"triangle";o.frequency.setValueAtTime(kind==="kick"?155:kind==="snare"?240:430,t);o.frequency.exponentialRampToValueAtTime(kind==="kick"?47:kind==="snare"?100:210,t+.1);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+(kind==="kick"?.2:.075));o.connect(g);g.connect(music);o.start(t);o.stop(t+.23)}
const melody=[76,null,79,81,79,76,74,null,72,74,76,null,79,76,74,null,76,79,81,83,81,null,79,76,74,null,72,74,76,null,72,null];
const battleMelody=[57,60,64,null,57,60,67,64,55,59,62,null,55,59,67,62,57,60,64,69,67,64,60,null,55,59,62,67,64,62,59,null];
const bossMelody=[57,null,69,68,67,null,64,62,57,60,64,67,69,null,72,71,69,68,67,64,62,null,60,59,57,60,64,69,72,71,69,null];
const chords=[[48,52,55],[45,48,52],[50,53,57],[43,47,50]];
function tick(){if(!enabled||!ctx||ctx.state!=="running"||preference==="silent")return;const i=step++,at=next;next+=scene==="world"?.25:scene==="boss"?.145:.165;
if(scene==="world"){const note=melody[i%32];if(note!==null)pluck(note,at,i%4===0?.24:.17);if(i%8===0){const ch=chords[Math.floor(i/8)%4];ch.forEach(n=>pad(n,at,1.8,.055));pluck(ch[0]-12,at,.13)}if(i%8===4)pluck(84,at,.065)}
else{const boss=scene==="boss",note=(boss?bossMelody:battleMelody)[i%32];if(note!==null){voice(midi(note),.18,boss?"sawtooth":"triangle",boss?.17:.15,at);voice(midi(note+12),.09,"sine",.06,at)}if(i%2===0)voice(midi((i%16<8?33:31)),.16,"sawtooth",.12,at);if(i%4===0)drum("kick",at,boss?.27:.2);if(i%8===4)drum("snare",at,.16);if(boss&&i%8===0){const ch=chords[Math.floor(i/8)%4];ch.forEach(n=>pad(n,at,1.05,.045))}}
}
function stop(){if(timer){clearInterval(timer);timer=null}if(music&&ctx){music.gain.cancelScheduledValues(ctx.currentTime);music.gain.setValueAtTime(music.gain.value,ctx.currentTime);music.gain.setTargetAtTime(.0001,ctx.currentTime,.035)}}
function start(){stop();if(!enabled||preference==="silent"||!init())return;step=0;next=ctx.currentTime+.08;music.gain.setTargetAtTime(preference==="focus"?.18:.6,ctx.currentTime,.12);const pump=()=>{if(!ctx||ctx.state!=="running")return;while(next<ctx.currentTime+.22)tick()};pump();timer=setInterval(pump,65)}
function setMode(m){scene=m==="battle"||m==="boss"?m:"world";if(enabled&&ctx&&ctx.state==="running")start()}
function setPreference(p){if(!["epic","focus","silent"].includes(p))return;preference=p;try{localStorage.setItem(M,p)}catch{}if(preference==="silent")stop();else if(enabled)start();update();return preference}
function update(){document.querySelectorAll("[data-audio-toggle]").forEach(b=>{b.textContent=enabled?(preference==="silent"?"🔇 無音":"🔊 音楽 ON"):"🔇 音楽 OFF";b.setAttribute("aria-pressed",String(enabled))});document.querySelectorAll("[data-audio-mode]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.audioMode===preference)))}
function toggle(){enabled=!enabled;try{localStorage.setItem(K,enabled?"1":"0")}catch{}if(enabled)start();else stop();update();return enabled}
function effect(name){if(!enabled||preference==="silent"||!ctx||ctx.state!=="running")return;const t=ctx.currentTime;if(name==="place"){voice(523,.2,"sine",.23,t,master);voice(784,.28,"sine",.16,t+.08,master)}else if(name==="attack"){voice(165,.14,"sawtooth",.3,t,master);voice(92,.23,"triangle",.32,t+.07,master)}else if(name==="correct"){[523,659,784,1046].forEach((n,i)=>voice(n,.21,"triangle",.25,t+i*.08,master))}else if(name==="win"){[392,523,659,784,1046].forEach((n,i)=>voice(n,.36,"triangle",.32,t+i*.13,master))}else if(name==="clear"){[392,523,659,784].forEach((n,i)=>voice(n,.24,"sine",.24,t+i*.12,master))}else if(name==="wrong"){voice(220,.2,"triangle",.15,t,master);voice(196,.26,"triangle",.12,t+.14,master)}}
function mount(m){scene=m==="battle"||m==="boss"?m:"world";const holder=document.createElement("div");holder.style.cssText="position:fixed;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:10;display:flex;gap:5px;align-items:flex-end";const menu=document.createElement("div");menu.hidden=true;menu.style.cssText="position:absolute;bottom:49px;right:0;width:155px;padding:7px;border:1px solid #d6b87c;border-radius:12px;background:#17283c;box-shadow:0 8px 24px #0009";for(const [id,label] of [["epic","🔥 熱血"],["focus","🧠 集中"],["silent","🔇 無音"]]){const b=document.createElement("button");b.type="button";b.dataset.audioMode=id;b.textContent=label;b.style.cssText="display:block;width:100%;padding:9px;border:0;background:transparent;color:#ffe8b5;text-align:left;font:700 12px system-ui";b.onclick=()=>{setPreference(id);menu.hidden=true};menu.append(b)}const btn=document.createElement("button");btn.type="button";btn.dataset.audioToggle="";btn.style.cssText="border:1px solid #e3bf7b;border-radius:12px;background:#172a3e;color:#ffe6aa;padding:10px;font:700 12px system-ui;cursor:pointer;min-height:42px";btn.onclick=toggle;const settings=document.createElement("button");settings.type="button";settings.textContent="🎚️";settings.setAttribute("aria-label","音楽モードを選ぶ");settings.style.cssText=btn.style.cssText;settings.onclick=()=>{menu.hidden=!menu.hidden};holder.append(menu,settings,btn);document.body.append(holder);update();if(enabled){const wake=()=>{if(enabled)start();document.removeEventListener("pointerdown",wake)};document.addEventListener("pointerdown",wake,{once:true})}document.addEventListener("visibilitychange",()=>{if(document.hidden)stop();else if(enabled)start()});window.addEventListener("pagehide",stop)}
window.RealLineAudio={mount,effect,setMode,setPreference,toggle};})();
